name: Docker Compose Build and Health Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [KU]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose -f deploy/production/docker-compose.production.yml build

      - name: Run Unit Tests
        id: run-tests  # Add an ID to this step for referencing
        run: |
          docker compose -f deploy/production/docker-compose.production.yml -p testing-build up --exit-code-from unit-test --abort-on-container-exit
          
      - name: Check Unit Test Result
        run: |
          if [ "${{ steps.run-tests.outcome }}" == "failure" ]; then
            echo "Unit tests failed, stopping the workflow."
            exit 1  # Fail the workflow if tests fail
          fi

      - name: Check running containers
        run: docker ps
