name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [KU]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Run Unit Tests
    #   run: |
    #     docker compose -f deploy/production/docker-compose.production.yml up -p testing --exit-code-from unit-test
    #   continue-on-error: true  # Allow the workflow to proceed even if this step fails

    # - name: Check if Unit Tests Passed
    #   id: check-tests
    #   run: |
    #     if [ $? -ne 0 ]; then
    #       echo "Unit tests failed, stopping the workflow."
    #       exit 1  # Fail the workflow if tests fail
    #     fi
    
    - name: Stop and remove existing containers
      run: |
        docker compose -f deploy/production/docker-compose.production.yml down

    - name: Create .env file for requester service
      run: |
        echo "CLIENT_ID_GOOGLE=${{ secrets.CLIENT_ID_GOOGLE }}" >> services/requester/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> services/requester/.env
        echo "PAYMENT_API=${{ secrets.PAYMENT_API }}" >> services/requester/.env
        echo "PAYMENT_API_SECRET=${{ secrets.PAYMENT_API_SECRET }}" >> services/requester/.env

    - name: Build and start Docker containers
      run: |
        docker compose -f deploy/production/docker-compose.production.yml up --build -d

    - name: Check running containers
      run: docker ps
